### ISSUE TITLE
Wrong multiplication in GF(2^8)

### ISSUE THREAD

**Issue by mlialin** [emin63/pyfinite#14]
I bumped into wrong result of multiplication trying to calculate `0xFF * 0x2` in Galois Field 2^8. 
So, I did:
`
f = ffield.FField(8, gen=0x11B)
`
`res = f.Multiply(0xFF, 2)
`
and got `res = 227` while expected `res = 229`.

It seems that `f.generator` is equal to the **default** value `0x11D` for GF(2^8), but test of set generator returns value `0x11B`.

I ran pyfinite 1.9 from anaconda in jupyter notebook

**Comment by GerfautGE** [comment]
I I had no problem.
I obtain `229` as a result of `f.Multiply(0xff, 2)`
I ran 1.9 like you and it seems working.

have you a more complex program that may cause the issue ?

**Comment by mlialin** [comment]
Actually, no.
The fact is that I was testing a function written in C and noticed an unexpected result when executing:
```
f = ffield.FField(64, gen=0x1000000000000001B, useLUT=-1)
res = f.Multiply(0xFFFFFFFFFFFFFFFF, 2)
```
Next, I intentionally simplified the function to work with a shorter example (initial comment). 
However, since in both examples there is an overflow above the highest degree of the generator, an exclusive OR must be performed. The last bytes of the generators match. 

As result in both of these examples the lowest byte must be equal to the `229` or in hex `0xE5`. And now I see that in GF(2^8) `f.Multiply(0xFF, 2)` returns `227` while least significant byte in GF(2^64) `f.Multiply(0xFFFFFFFFFFFFFFFF, 2)` is `229`. The second is correct while first is not.

**Comment by emin63** [comment]
@mlialin , @GerfautGE : thanks for your interest in pyfinite.

I think you are both right (and perhaps I am wrong): the issue seems to be a lookup table issue.

Please see PR https://github.com/emin63/pyfinite/pull/15 and the new `tests/lut_example.py` for an illustration of what I think is going on. Basically, `pyfinite` is trying to be helpful by using a lookup table but seems like it is seeing one for a different generator. You can either remove the old lookup table or disable use of lookup tables.

If you would like to take a look at PR #15 and let me know if you have any feedback, that would be much appreciated.

Thanks.

**Comment by mlialin** [comment]
The suggested in PR https://github.com/emin63/pyfinite/pull/15 disabling the use of lookup tables `f=ffield.FField(8, gen=0x11B, useLUT=0)` helped. 
`f.Multiply(0xFF, 2)` now returns the correct result.

@emin63, @GerfautGE : thanks for your help!
