### ISSUE TITLE
GF(2^163)

### ISSUE THREAD

**Issue by IssaIssa1** [emin63/pyfinite#4]
I am trying to apply polynomial arithmetics in GF(2^163). I tried to generate the field using your code but it's returning an error. What's your thoughts on dealing with high order GFs.

**Comment by emin63** [comment]
All you need to do is find the appropriate primitive polynomial and either use that or submit a pull request with the information and I can add it.

Thanks and good luck.

**Comment by IssaIssa1** [comment]
I already have it (please find it in the image attached below). But how I may integrate it into your code?


![Primi  Poly](https://user-images.githubusercontent.com/35012871/70851943-8b5fc280-1ea4-11ea-8362-91f643321860.png)

**Comment by emin63** [comment]
Sorry, I didn't see your reply since you posted in a closed ticket.

To add a new primitive polynomial, add to the `gPrimitivePolysCondensed` variable in `ffield.py`. For example, if you look at the element
```python
    97 : (97,6,0),
```
It is saying the 97th degree primitive polynomial is `p(t) = t^97 + t^6 + 1`. If you want to add a degree 163 polynomial of the form `p(t) = t^163 + t^7 + t^6 + t^3 +1` you would add an element to `gPrimitivePolysCondensed` like
```python
    163: (163, 7, 6, 3, 0)
```
